CREATE VIEW Arrivals AS 

WITH DOC_1 AS(

SELECT 
	[ORDER_MONTH],
	[MOTO_ID],
	[MOTORCYCLE],
	[ETA],
	[UNITs],
	[FACTORY]
FROM 
	dbo.[DOC_1_ORIGINAL_SQL_TABLE]
WHERE
	[Factory] = 'factory_A'
		
), CTE_DOC_2 AS(

   SELECT
	[ORDER_MONTH],    	
	[Invoice],
	[MOTORCYCLE], 
	[Units],
	[Date of Upload],
	[ETA]
   FROM 
	dbo.[DOC_2_ORIGINAL_SQL_TABLE]
   WHERE 
	[Factory] = 'factory_A'
   AND
	[Date of Upload] = (SELECT MAX([Date of Upload])
			    FROM dbo.[DOC_2_ORIGINAL_SQL_TABLE]
			    WHERE [Factory] = 'factory_A')  
        
), DOC_2 AS(

SELECT 
	[ORDER_MONTH],
	[Invoice],
   	[MOTORCYCLE],
	[ETA],
   	SUM([Units]) AS [Unidades DOC_2]
FROM 
	CTE_DOC_2
GROUP BY 
	[ORDER_MONTH],
	[Invoice],
	[MOTORCYCLE],
	[ETA]

), DOC_3 AS(

SELECT 
	[INVOICE],
	[MOTORCYCLE],
	[UNITS],
	[DATE-PLANNED],
	[CONTAINER],
	[DATE OF UPLOAD],
	MAX([DATE OF UPLOAD]) OVER (PARTITION BY [INVOICE], [MOTORCYCLE], [CONTAINER], [UNITS]) AS MAX_DATE
FROM
	dbo.[DOC_3_ORIGINAL_SQL_TABLE]
WHERE 
	[Factory] = 'factory_A'
				
), acc_DOC_3 AS (

SELECT
	[INVOICE],
	[MOTORCYCLE],
	[UNITS],
	[DATE-PLANNED],
	[CONTAINER],
	[DATE OF UPLOAD]
FROM
	DOC_3
WHERE
	[DATE OF UPLOAD] = MAX_DATE
	
), agg_DOC_3 AS(

SELECT
	LEFT([INVOICE], LEN([INVOICE]) - 2) AS PO,
	[INVOICE],
	[MOTORCYCLE],
	[DATE-PLANNED],
	[CONTAINER],
	SUM([UNITS]) AS UNITS
FROM
	acc_DOC_3
GROUP BY 
	LEFT([INVOICE], LEN([INVOICE]) - 2),
	[INVOICE],
	[MOTORCYCLE],
	[DATE-PLANNED],
	[CONTAINER]

), vlookup AS (

SELECT DISTINCT
	LEFT([Invoice], LEN([Invoice]) - 2) AS PO,
	[ORDER_MONTH]
FROM 
	dbo.[DOC_2_ORIGINAL_SQL_TABLE]
WHERE
	[Factory] = 'factory_A'
	
), DOC_3_vlookup AS (

SELECT 
	v.[ORDER_MONTH],
	a.[INVOICE],
	a.[MOTORCYCLE],
	a.[DATE-PLANNED],
	a.[UNITS],
	a.[CONTAINER]
	
FROM 
	agg_DOC_3 a

LEFT JOIN 
	vlookup v
	
ON 	
	a.[PO] = v.[PO]
	
), DOC_3_DOC_2 AS (

SELECT 
	b.[ORDER_MONTH] AS ORDER_MONTH_DOC_2,
	v.[ORDER_MONTH] AS ORDER_MONTH_DOC_3,
	CASE
		WHEN v.[ORDER_MONTH] IS NOT NULL THEN v.[ORDER_MONTH]
		WHEN v.[ORDER_MONTH] IS NULL THEN b.[ORDER_MONTH]
	END AS [ORDER_MONTH],
	b.[Invoice] AS INVOICE_DOC_2,
	v.[INVOICE] AS INVOICE_DOC_3,
	CASE
		WHEN v.[INVOICE] IS NOT NULL THEN v.[INVOICE]
		WHEN v.[INVOICE] IS NULL THEN b.[Invoice]
	END AS [INVOICE],
	b.[MOTORCYCLE] AS MOTORCYCLE_DOC_2,
	v.[MOTORCYCLE] AS MOTORCYCLE_DOC_3,
	CASE
		WHEN v.[MOTORCYCLE] IS NOT NULL THEN v.[MOTORCYCLE]
		WHEN v.[MOTORCYCLE] IS NULL THEN b.[MOTORCYCLE]
	END AS [MOTORCYCLE],
	b.[Unidades DOC_2],
	v.[UNITS] AS [Unidades DOC_3],
	CASE
		WHEN v.[UNITS] IS NOT NULL THEN v.[UNITS]
		WHEN v.[UNITS] IS NULL THEN b.[Unidades DOC_2]
	END AS [Unidades],
	b.[ETA] AS [ETA DOC_2],
	v.[DATE-PLANNED] AS [DATE-PLANNED DOC_3],
	CASE
		WHEN v.[DATE-PLANNED] IS NOT NULL THEN v.[DATE-PLANNED]
		WHEN v.[DATE-PLANNED] IS NULL THEN b.[ETA]
	END AS [Fecha estimada],
	v.[CONTAINER]
	
FROM
	DOC_2 b

FULL JOIN
	DOC_3_vlookup v
	
ON
	b.[MOTORCYCLE] = v.[MOTORCYCLE]
AND
	b.[Invoice] = v.[INVOICE]
		
), DOC_4 AS(

SELECT 
	[INVOICE],
	[CONTAINER],
	[ARRIVAL_DATE],
	[DATE_OF_UPLOAD],
	MAX([DATE_OF_UPLOAD]) OVER (PARTITION BY [INVOICE], [CONTAINER]) AS MAX_DATE
FROM
	dbo.[DOC_4_ORIGINAL_SQL_TABLE]

), acc_DOC_4 AS(

SELECT
	[INVOICE],
	[CONTAINER],
	[ARRIVAL_DATE],
	[DATE_OF_UPLOAD]
FROM
	DOC_4
WHERE
	[DATE_OF_UPLOAD] = MAX_DATE

), DOC_1_DOC_2_DOC_3_DOC_4 AS (

SELECT
	c.[ORDER_MONTH],
	c.[MOTO_ID],
	c.[MOTORCYCLE],
	v.[INVOICE],
	v.[CONTAINER],
	c.[UNITs],
	v.[Unidades DOC_2],
	v.[Unidades DOC_3],
	CASE
		WHEN v.[Unidades] IS NOT NULL THEN v.[Unidades]
		WHEN v.[Unidades] IS NULL THEN c.[UNITs]
	END AS [Unidades],
	c.[ETA] AS [ETA DOC_1],
	v.[ETA DOC_2],
	v.[DATE-PLANNED DOC_3] AS [ETA DOC_3],
	p.[ARRIVAL_DATE],
	CASE
		WHEN p.[ARRIVAL_DATE] IS NOT NULL THEN p.[ARRIVAL_DATE]
		WHEN p.[ARRIVAL_DATE] IS NULL AND v.[DATE-PLANNED DOC_3] IS NOT NULL THEN v.[DATE-PLANNED DOC_3]
		WHEN p.[ARRIVAL_DATE] IS NULL AND v.[DATE-PLANNED DOC_3] IS NULL AND v.[ETA DOC_2] <> '1900-01-01' THEN v.[ETA DOC_2]
		WHEN p.[ARRIVAL_DATE] IS NULL AND v.[DATE-PLANNED DOC_3] IS NULL AND (v.[ETA DOC_2] IS NULL OR v.[ETA DOC_2] = '1900-01-01') THEN c.[ETA]
	END AS [Fecha de llegada],
	c.[FACTORY]
	
	FROM
		DOC_3_DOC_2 v
		
	RIGHT JOIN
		DOC_1 c
	ON 
		v.[ORDER_MONTH] = c.[ORDER_MONTH]
	AND
		v.[MOTORCYCLE] = c.[MOTORCYCLE]
		
	LEFT JOIN
		acc_DOC_4 p
	ON
		v.[INVOICE] = p.[INVOICE]
	AND
		v.[CONTAINER] = p.[CONTAINER]

)

SELECT 
   *,
   DATEPART(WEEK, [Fecha de llegada]) - DATEPART(WEEK, DATEADD(MONTH, DATEDIFF(MONTH, 0, [Fecha de llegada]), 0)) + 1 AS SemanaDelMes
 
FROM DOC_1_DOC_2_DOC_3_DOC_4

