CREATE VIEW consistent_info AS

WITH DOC_3 AS(

SELECT 
	[INVOICE],
	[MOTORCYCLE],
	[UNITS],
	[DATE OF UPLOAD],
	MAX([DATE OF UPLOAD]) OVER (PARTITION BY [INVOICE], [MOTORCYCLE], [CONTAINER], [UNITS]) AS MAX_DATE
FROM
	dbo.[DOC_3_ORIGINAL_SQL_TABLE]
WHERE 
	[Factory] = 'factory_A'
				
), acc_DOC_3 AS (

SELECT
	[INVOICE],
	[MOTORCYCLE],
	[UNITS],
	[DATE OF UPLOAD]
FROM
	DOC_3
WHERE
	[DATE OF UPLOAD] = MAX_DATE
	
), agg_DOC_3 AS(

SELECT
	LEFT([INVOICE], LEN([INVOICE]) - 2) AS PO,
	[INVOICE],
	[MOTORCYCLE],
	SUM([UNITS]) AS UNITS
FROM
	acc_DOC_3
GROUP BY 
	LEFT([INVOICE], LEN([INVOICE]) - 2),
	[INVOICE],
	[MOTORCYCLE]
	
), filt_DOC_2 AS (
	
SELECT 
	[ORDER_MONTH],
	[MOTORCYCLE],
	[INVOICE],
	[UNITS]
FROM 
	dbo.[DOC_2_ORIGINAL_SQL_TABLE]
WHERE
	[Date Of Upload] = (SELECT MAX([Date Of Upload])
			    FROM dbo.[DOC_2_ORIGINAL_SQL_TABLE]
			    WHERE [Factory] = 'factory_A') 
AND
	[Factory] = 'factory_A'
		
), grouped_DOC_2 AS (
	
SELECT 
	[ORDER_MONTH],
	[MOTORCYCLE],
	[INVOICE],
	SUM([UNITS]) AS [UNIDADES]
FROM 
	filt_DOC_2
GROUP BY 
	[ORDER_MONTH],
	[MOTORCYCLE],
	[INVOICE]

), union_DOC_2_DOC_3 AS (

SELECT 
	v.[PO],
	b.[ORDER_MONTH],
	v.[INVOICE] AS INVOICE_DOC_3,
	b.[INVOICE] AS INVOICE_DOC_2,
	CASE
		WHEN v.[INVOICE] IS NOT NULL THEN v.[INVOICE]
		WHEN v.[INVOICE] IS NULL THEN b.[INVOICE]
	END AS [INVOICE],
	v.[MOTORCYCLE] AS MOTORCYCLE_DOC_3,
	b.[MOTORCYCLE] AS MOTORCYCLE_DOC_2,
	CASE
		WHEN v.[MOTORCYCLE] IS NOT NULL THEN v.[MOTORCYCLE]
		WHEN v.[MOTORCYCLE] IS NULL THEN b.[MOTORCYCLE]
	END AS [MOTORCYCLE],
	v.[UNITS] AS UNITS_DOC_3,
	b.[UNIDADES] AS UNITS_DOC_2,
	CASE
		WHEN v.[UNITS] = b.[UNIDADES] THEN 'Iguales'
		WHEN v.[UNITS] = b.[UNIDADES] THEN 'Diferentes'
	END AS [Chivato],
	CASE 
		WHEN v.[UNITS] IS NOT NULL THEN v.[UNITS]
		WHEN v.[UNITS] IS NULL THEN b.[UNIDADES]
	END AS [UNIDADES TOTALES]
			
FROM
	agg_DOC_3 v
FULL JOIN
	grouped_DOC_2 b
ON 
	v.[INVOICE] = b.[Invoice]
AND
	v.[MOTORCYCLE] = b.[MOTORCYCLE]

), vlookup AS (

SELECT DISTINCT
	LEFT([Invoice], LEN([Invoice]) - 2) AS PO,
	[ORDER_MONTH]
FROM 
	dbo.[DOC_2_ORIGINAL_SQL_TABLE]
WHERE 
	[Factory] = 'factory_A'
	
	
), DOC_3_DOC_2_agg AS (

SELECT
	v.[ORDER_MONTH] AS [ORDER_MONTH_vlookup],
	u.[ORDER_MONTH],
	CASE
		WHEN v.[ORDER_MONTH] IS NULL THEN u.[ORDER_MONTH]
		WHEN u.[ORDER_MONTH] IS NULL THEN v.[ORDER_MONTH]
		WHEN v.[ORDER_MONTH] IS NOT NULL AND u.[ORDER_MONTH] IS NOT NULL THEN v.[ORDER_MONTH] 
	END AS [ORDER_MONTH_FINAL],
	u.[INVOICE_DOC_3],
	u.[INVOICE_DOC_2],
	u.[INVOICE],
	u.[MOTORCYCLE_DOC_3],
	u.[MOTORCYCLE_DOC_2],
	u.[MOTORCYCLE],
	u.[UNITS_DOC_3],
	u.[UNITS_DOC_2],
	u.[Chivato],
	u.[UNIDADES TOTALES]
FROM 
	union_DOC_2_DOC_3 u	
LEFT JOIN
	vlookup v
ON
	u.[PO] = v.[PO]
	
), DOC_3_DOC_2_group AS (
	
SELECT
	[ORDER_MONTH_FINAL] AS [ORDER_MONTH],
	[MOTORCYCLE],
	SUM([UNIDADES TOTALES]) AS [UNIDADES DOC_2 + DOC_3]
FROM
	DOC_3_DOC_2_agg
GROUP BY 
	[ORDER_MONTH_FINAL],
	[MOTORCYCLE]
		
), DOC_1 AS (

SELECT
	[ORDER_MONTH],
	[MATERIAL],
	[MOTORCYCLE],
	[UNITS]
FROM
	dbo.[DOC_1_ORIGINAL_SQL_TABLE]
WHERE 
	[Factory] = 'factory_A'

), DOC_1_DOC_2_DOC_3 AS (
	
SELECT
	CASE
		WHEN c.[ORDER_MONTH] IS NULL THEN v.[ORDER_MONTH]
		WHEN v.[ORDER_MONTH] IS NULL THEN c.[ORDER_MONTH]
		WHEN v.[ORDER_MONTH] IS NOT NULL AND c.[ORDER_MONTH] IS NOT NULL THEN c.[ORDER_MONTH]
	END AS [ORDER_MONTH],
	c.[MATERIAL],
	CASE
		WHEN c.[MOTORCYCLE] IS NULL THEN v.[MOTORCYCLE]
		WHEN v.[MOTORCYCLE] IS NULL THEN c.[MOTORCYCLE]
		WHEN v.[MOTORCYCLE] IS NOT NULL AND c.[MOTORCYCLE] IS NOT NULL THEN c.[MOTORCYCLE]
	END AS [MOTORCYCLE],		
	c.[UNITS] AS [Unidades DOC_1],
	v.[UNIDADES DOC_2 + DOC_3],
	CASE
		WHEN c.[UNITS] = v.[UNIDADES DOC_2 + DOC_3] THEN 'Iguales'
		WHEN c.[UNITS] <> v.[UNIDADES DOC_2 + DOC_3] THEN 'Diferentes'
	END AS [Chequeo]
FROM
	DOC_1 c
		
FULL OUTER JOIN
	DOC_3_DOC_2_group v
ON 
	v.[ORDER_MONTH] = c.[ORDER_MONTH]
AND
	v.[MOTORCYCLE] = c.[MOTORCYCLE]
)

SELECT * 
FROM
	DOC_1_DOC_2_DOC_3
